Repository Justin217X/MonsterMash, pull requests merged in 2024-11, with the labels that each got.

#3 Updated Readme for the 3rd time!
  README.md
Labels: documentation

#8 Implemented Enemy AI
  Enemy/enemy.gd
  Enemy/enemy.tscn
  Player/player.gd
  Player/player.tscn
  World/world.tscn
  project.godot
Labels: enhancement

#11 Implemented EnemySpawner
  Player/player.tscn
  Utility/enemy_spawner.gd
  Utility/enemy_spawner.tscn
  Utility/spawn_info.gd
  World/world.tscn
Labels: enhancement

#12 Implemented HitBoxes and HurtBoxes
  Enemy/enemy.gd
  Enemy/enemy.tscn
  Player/player.gd
  Player/player.tscn
  Utility/hit_box.gd
  Utility/hit_box.tscn
  Utility/hurt_box.gd
  Utility/hurt_box.tscn
  project.godot
Labels: enhancement

#13 Updated project setting
  project.godot
  scene/world.tscn
Labels: enhancement

#14 Update enemy_spawner.gd
  Utility/enemy_spawner.gd
Labels: bug

#15 Created and implemented an IceSpear Attack
  Enemy/enemy.tscn
  Player/Attack/ice_spear.gd
  Player/Attack/ice_spear.tscn
  Player/player.gd
  Player/player.tscn
  Utility/hurt_box.gd
  World/world.tscn
Labels: enhancement

#16 Created and Implemented Experience
  Enemy/enemy.gd
  Enemy/enemy.tscn
  Objects/experience_gem.gd
  Objects/experience_gem.tscn
  Player/Attack/ice_spear.gd
  Player/player.gd
  Player/player.tscn
  Utility/hurt_box.gd
  World/world.tscn
  assets/blue_gem.png
  assets/blue_gem.png.import
  assets/exp_background.png
  assets/exp_background.png.import
  assets/exp_progress.png
  assets/exp_progress.png.import
  assets/gems.png
  assets/gems.png.import
  assets/green_gem.png
  assets/green_gem.png.import
  assets/red_gem.png
  assets/red_gem.png.import
  project.godot
Labels: enhancement
